/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COORDINATES_DATA_PB_H_INCLUDED
#define PB_COORDINATES_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _coordinates_data
{
    uint32_t device_id;
    uint32_t type;
    float x;
    float y;
    uint64_t timestamp_ms;
} coordinates_data;

#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define coordinates_data_init_default {0, 0, 0, 0, 0}
#define coordinates_data_init_zero {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define coordinates_data_device_id_tag 1
#define coordinates_data_type_tag 2
#define coordinates_data_x_tag 3
#define coordinates_data_y_tag 4
#define coordinates_data_timestamp_ms_tag 5

/* Struct field encoding specification for nanopb */
#define coordinates_data_FIELDLIST(X, a)         \
    X(a, STATIC, SINGULAR, UINT32, device_id, 1) \
    X(a, STATIC, SINGULAR, UINT32, type, 2)      \
    X(a, STATIC, SINGULAR, FLOAT, x, 3)          \
    X(a, STATIC, SINGULAR, FLOAT, y, 4)          \
    X(a, STATIC, SINGULAR, UINT64, timestamp_ms, 5)
#define coordinates_data_CALLBACK NULL
#define coordinates_data_DEFAULT NULL

    extern const pb_msgdesc_t coordinates_data_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define coordinates_data_fields &coordinates_data_msg

/* Maximum encoded size of messages (where known) */
#define COORDINATES_DATA_PB_H_MAX_SIZE coordinates_data_size
#define coordinates_data_size 33

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif